#!/bin/bash

# Generate cron wrapper to set correct environment variables
cat > /var/www/apps/sntracker/cronwrapper << EOF
export PYTHONPATH="${PYTHONPATH}"
export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}"

export SNTRACKER_DB_NAME="${SNTRACKER_DB_NAME}"
export SNTRACKER_DB_HOST="${SNTRACKER_DB_HOST}"
export SNTRACKER_DB_USER="${SNTRACKER_DB_USER}"
export SNTRACKER_DB_PASSWD="${SNTRACKER_DB_PASSWD}"
export SNTRACKER_API_USER="${SNTRACKER_API_USER}"
export SNTRACKER_API_PASSWD="${SNTRACKER_API_PASSWD}"
export SNTRACKER_EMAIL_USERNAME="${SNTRACKER_EMAIL_USERNAME}"
export SNTRACKER_EMAIL_PASSWORD="${SNTRACKER_EMAIL_PASSWORD}"
export PROPOSAL_USER="${PROPOSAL_USER}"
export PROPOSAL_PASSWD="${PROPOSAL_PASSWD}"
export PROPOSAL_CODE="${PROPOSAL_CODE}"

EOF

# Make cron wrapper executable
chmod +x /var/www/apps/sntracker/cronwrapper
chmod 777 /var/www/apps/sntracker/*.log

# Setup the LCO Supernova Tracker webapp
python /var/www/apps/sntracker/manage.py migrate --noinput
# python /var/www/apps/sntracker/manage.py supernovae/fixtures/loaddata initial_data.json
python /var/www/apps/sntracker/manage.py collectstatic --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
