#!/bin/bash

# Generate cron wrapper to set correct environment variables
cat > /var/www/apps/asteroidday/cronwrapper << EOF
export PYTHONPATH="${PYTHONPATH}"
export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}"

export SUPERNOVA_DB_NAME="${SUPERNOVA_DB_NAME}"
export SUPERNOVA_DB_HOST="${SUPERNOVA_DB_HOST}"
export SUPERNOVA_DB_USER="${SUPERNOVA_DB_USER}"
export SUPERNOVA_DB_PASSWD="${SUPERNOVA_DB_PASSWD}"
export SUPERNOVA_API_USER="${SUPERNOVA_API_USER}"
export SUPERNOVA_API_PASSWD="${SUPERNOVA_API_PASSWD}"
export SUPERNOVA_EMAIL_USERNAME="${SUPERNOVA_EMAIL_USERNAME}"
export SUPERNOVA_EMAIL_PASSWORD="${SUPERNOVA_EMAIL_PASSWORD}"

EOF

# Make cron wrapper executable
chmod +x /var/www/apps/sntracker/cronwrapper

# Setup the LCOGT Asteroid day webapp
python /var/www/apps/sntracker/manage.py migrate --noinput
python /var/www/apps/sntracker/manage.py collectstatic --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
