# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('repeats', models.IntegerField(default=0)),
                ('aperture', models.CharField(max_length=4)),
                ('exposure_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_num', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('S', 'Scheduled'), ('N', 'Canceled'), ('F', 'Failed')], max_length=1)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email address of the submitter')),
                ('request_ids', models.TextField(blank=True, null=True)),
                ('frame_ids', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supernova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Designation')),
                ('filter_name', models.CharField(max_length=10)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('teaser', models.CharField(max_length=120)),
                ('image', models.CharField(default='no-image.jpg', max_length=50)),
                ('timelapse_url', models.URLField()),
                ('num_observations', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='supernova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.Supernova'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='supernova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.Supernova'),
        ),
    ]
