# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0002_remove_supernova_filter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposure',
            old_name='name',
            new_name='filter_name',
        ),
        migrations.AlterField(
            model_name='exposure',
            name='aperture',
            field=models.CharField(choices=[('0m4', '0.4-meter'), ('1m4', '1.0-meter'), ('2m4', '2.0-meter')], max_length=4),
        ),
    ]
