# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0004_auto_20161214_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supernova',
            name='num_observations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supernova',
            name='timelapse_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
