# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0006_supernova_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supernova',
            name='dec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supernova',
            name='ra',
            field=models.FloatField(default=0.0),
        ),
    ]
