# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0007_auto_20161215_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='aperture',
            field=models.CharField(choices=[('0m4', '0.4-meter'), ('1m0', '1.0-meter'), ('2m0', '2.0-meter')], max_length=4),
        ),
    ]
