# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0008_auto_20161215_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='instrument',
            field=models.CharField(choices=[('1M0-SCICAM-SBIG', '1m Science Camera'), ('1M0-SCICAM-SINISTRO', 'Sinistro'), ('2M0-SCICAM-SPECTRAL', 'Spectral'), ('2M0-SCICAM-MEROPE', 'Merope')], default='1M0-SCICAM-SINISTRO', max_length=20),
            preserve_default=False,
        ),
    ]
