# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0009_exposure_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supernova',
            name='image',
            field=models.FileField(upload_to='teaser'),
        ),
    ]
