# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0011_auto_20170111_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='supernova',
            name='repeat_interval',
            field=models.FloatField(default=14.0, help_text='window from today that the request will be posted'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='instrument',
            field=models.CharField(choices=[('0M4-SCICAM-SBIG', '0.4m Science Camera'), ('1M0-SCICAM-SINISTRO', 'Sinistro'), ('2M0-SCICAM-SPECTRAL', 'Spectral'), ('2M0-SCICAM-MEROPE', 'Merope')], max_length=20),
        ),
    ]
